// <auto-generated />
namespace Pitch.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Many_to_many_attempt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Many_to_many_attempt));
        
        string IMigrationMetadata.Id
        {
            get { return "201503192033328_Many_to_many_attempt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
