// <auto-generated />
namespace Pitch.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class ICollections_on_profile_model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ICollections_on_profile_model));
        
        string IMigrationMetadata.Id
        {
            get { return "201503191617112_ICollections_on_profile_model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
