// <auto-generated />
namespace Pitch.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Model_CSVs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Model_CSVs));
        
        string IMigrationMetadata.Id
        {
            get { return "201503152315259_Model_CSVs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
